/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import hourmaze.Celda;
import hourmaze.Solucion;
import hourmaze.Tablero;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author joaquin
 */
public class HourMaze extends javax.swing.JFrame {

    /**
     * Creates new form HourMaze
     */
    public HourMaze() {
        initComponents();
        inicializaGUI();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        jLabel24_00 = new javax.swing.JLabel();
        jLabel24_01 = new javax.swing.JLabel();
        jLabel24_02 = new javax.swing.JLabel();
        jLabel24_03 = new javax.swing.JLabel();
        jLabel24_04 = new javax.swing.JLabel();
        jLabel24_05 = new javax.swing.JLabel();
        jLabel24_10 = new javax.swing.JLabel();
        jLabel24_11 = new javax.swing.JLabel();
        jLabel24_12 = new javax.swing.JLabel();
        jLabel24_13 = new javax.swing.JLabel();
        jLabel24_14 = new javax.swing.JLabel();
        jLabel24_15 = new javax.swing.JLabel();
        jLabel24_20 = new javax.swing.JLabel();
        jLabel24_21 = new javax.swing.JLabel();
        jLabel24_22 = new javax.swing.JLabel();
        jLabel24_23 = new javax.swing.JLabel();
        jLabel24_24 = new javax.swing.JLabel();
        jLabel24_25 = new javax.swing.JLabel();
        jLabel24_30 = new javax.swing.JLabel();
        jLabel24_31 = new javax.swing.JLabel();
        jLabel24_32 = new javax.swing.JLabel();
        jLabel24_33 = new javax.swing.JLabel();
        jLabel24_34 = new javax.swing.JLabel();
        jLabel24_35 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jBasePanel = new javax.swing.JPanel();
        jPanelTablero = new javax.swing.JPanel();
        jLabel60_00 = new javax.swing.JLabel();
        jLabel60_01 = new javax.swing.JLabel();
        jLabel60_02 = new javax.swing.JLabel();
        jLabel60_03 = new javax.swing.JLabel();
        jLabel60_04 = new javax.swing.JLabel();
        jLabel60_05 = new javax.swing.JLabel();
        jLabel60_06 = new javax.swing.JLabel();
        jLabel60_07 = new javax.swing.JLabel();
        jLabel60_08 = new javax.swing.JLabel();
        jLabel60_09 = new javax.swing.JLabel();
        jLabel60_10 = new javax.swing.JLabel();
        jLabel60_11 = new javax.swing.JLabel();
        jLabel60_12 = new javax.swing.JLabel();
        jLabel60_13 = new javax.swing.JLabel();
        jLabel60_14 = new javax.swing.JLabel();
        jLabel60_15 = new javax.swing.JLabel();
        jLabel60_16 = new javax.swing.JLabel();
        jLabel60_17 = new javax.swing.JLabel();
        jLabel60_18 = new javax.swing.JLabel();
        jLabel60_19 = new javax.swing.JLabel();
        jLabel60_20 = new javax.swing.JLabel();
        jLabel60_21 = new javax.swing.JLabel();
        jLabel60_22 = new javax.swing.JLabel();
        jLabel60_23 = new javax.swing.JLabel();
        jLabel60_24 = new javax.swing.JLabel();
        jLabel60_25 = new javax.swing.JLabel();
        jLabel60_26 = new javax.swing.JLabel();
        jLabel60_27 = new javax.swing.JLabel();
        jLabel60_28 = new javax.swing.JLabel();
        jLabel60_29 = new javax.swing.JLabel();
        jLabel60_30 = new javax.swing.JLabel();
        jLabel60_31 = new javax.swing.JLabel();
        jLabel60_32 = new javax.swing.JLabel();
        jLabel60_33 = new javax.swing.JLabel();
        jLabel60_34 = new javax.swing.JLabel();
        jLabel60_35 = new javax.swing.JLabel();
        jLabel60_36 = new javax.swing.JLabel();
        jLabel60_37 = new javax.swing.JLabel();
        jLabel60_38 = new javax.swing.JLabel();
        jLabel60_39 = new javax.swing.JLabel();
        jLabel60_40 = new javax.swing.JLabel();
        jLabel60_41 = new javax.swing.JLabel();
        jLabel60_42 = new javax.swing.JLabel();
        jLabel60_43 = new javax.swing.JLabel();
        jLabel60_44 = new javax.swing.JLabel();
        jLabel60_45 = new javax.swing.JLabel();
        jLabel60_46 = new javax.swing.JLabel();
        jLabel60_47 = new javax.swing.JLabel();
        jLabel60_48 = new javax.swing.JLabel();
        jLabel60_49 = new javax.swing.JLabel();
        jLabel60_50 = new javax.swing.JLabel();
        jLabel60_51 = new javax.swing.JLabel();
        jLabel60_52 = new javax.swing.JLabel();
        jLabel60_53 = new javax.swing.JLabel();
        jLabel60_54 = new javax.swing.JLabel();
        jLabel60_55 = new javax.swing.JLabel();
        jLabel60_56 = new javax.swing.JLabel();
        jLabel60_57 = new javax.swing.JLabel();
        jLabel60_58 = new javax.swing.JLabel();
        jLabel60_59 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButtonBorrar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonGenera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        HourMazeMenu = new javax.swing.JMenu();
        NuevoTableroMenu = new javax.swing.JMenu();
        Item24 = new javax.swing.JMenuItem();
        Item36 = new javax.swing.JMenuItem();
        Item48 = new javax.swing.JMenuItem();
        Item60 = new javax.swing.JMenuItem();
        InfoMenu = new javax.swing.JMenuItem();

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jPanel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel24.setLayout(new java.awt.GridLayout(4, 6));

        jLabel24_00.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_00.setText("00");
        jLabel24_00.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_00.setOpaque(true);
        jPanel24.add(jLabel24_00);

        jLabel24_01.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_01.setText("01");
        jLabel24_01.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_01.setOpaque(true);
        jPanel24.add(jLabel24_01);

        jLabel24_02.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_02.setText("02");
        jLabel24_02.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_02.setOpaque(true);
        jPanel24.add(jLabel24_02);

        jLabel24_03.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_03.setText("03");
        jLabel24_03.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_03.setOpaque(true);
        jPanel24.add(jLabel24_03);

        jLabel24_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_04.setText("04");
        jLabel24_04.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_04.setOpaque(true);
        jPanel24.add(jLabel24_04);

        jLabel24_05.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_05.setText("05");
        jLabel24_05.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_05.setOpaque(true);
        jPanel24.add(jLabel24_05);

        jLabel24_10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_10.setText("10");
        jLabel24_10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_10.setOpaque(true);
        jPanel24.add(jLabel24_10);

        jLabel24_11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_11.setText("11");
        jLabel24_11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_11.setOpaque(true);
        jPanel24.add(jLabel24_11);

        jLabel24_12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_12.setText("12");
        jLabel24_12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_12.setOpaque(true);
        jPanel24.add(jLabel24_12);

        jLabel24_13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_13.setText("13");
        jLabel24_13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_13.setOpaque(true);
        jPanel24.add(jLabel24_13);

        jLabel24_14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_14.setText("14");
        jLabel24_14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_14.setOpaque(true);
        jPanel24.add(jLabel24_14);

        jLabel24_15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_15.setText("15");
        jLabel24_15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_15.setOpaque(true);
        jPanel24.add(jLabel24_15);

        jLabel24_20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_20.setText("20");
        jLabel24_20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_20.setOpaque(true);
        jPanel24.add(jLabel24_20);

        jLabel24_21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_21.setText("21");
        jLabel24_21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_21.setOpaque(true);
        jPanel24.add(jLabel24_21);

        jLabel24_22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_22.setText("22");
        jLabel24_22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_22.setOpaque(true);
        jPanel24.add(jLabel24_22);

        jLabel24_23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_23.setText("23");
        jLabel24_23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_23.setOpaque(true);
        jPanel24.add(jLabel24_23);

        jLabel24_24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_24.setText("24");
        jLabel24_24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_24.setOpaque(true);
        jPanel24.add(jLabel24_24);

        jLabel24_25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_25.setText("25");
        jLabel24_25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_25.setOpaque(true);
        jPanel24.add(jLabel24_25);

        jLabel24_30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_30.setText("30");
        jLabel24_30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_30.setOpaque(true);
        jPanel24.add(jLabel24_30);

        jLabel24_31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_31.setText("31");
        jLabel24_31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_31.setOpaque(true);
        jPanel24.add(jLabel24_31);

        jLabel24_32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_32.setText("32");
        jLabel24_32.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_32.setOpaque(true);
        jPanel24.add(jLabel24_32);

        jLabel24_33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_33.setText("33");
        jLabel24_33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_33.setOpaque(true);
        jPanel24.add(jLabel24_33);

        jLabel24_34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_34.setText("34");
        jLabel24_34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_34.setOpaque(true);
        jPanel24.add(jLabel24_34);

        jLabel24_35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24_35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24_35.setText("35");
        jLabel24_35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jLabel24_35.setOpaque(true);
        jPanel24.add(jLabel24_35);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelTablero.setPreferredSize(new java.awt.Dimension(700, 450));
        jPanelTablero.setLayout(new java.awt.GridLayout(6, 10));

        jLabel60_00.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_00.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_00.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_00.setOpaque(true);
        jPanelTablero.add(jLabel60_00);

        jLabel60_01.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_01.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_01.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_01.setOpaque(true);
        jPanelTablero.add(jLabel60_01);

        jLabel60_02.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_02.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_02.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_02.setOpaque(true);
        jPanelTablero.add(jLabel60_02);

        jLabel60_03.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_03.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_03.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_03.setOpaque(true);
        jPanelTablero.add(jLabel60_03);

        jLabel60_04.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_04.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_04.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_04.setOpaque(true);
        jPanelTablero.add(jLabel60_04);

        jLabel60_05.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_05.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_05.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_05.setOpaque(true);
        jPanelTablero.add(jLabel60_05);

        jLabel60_06.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_06.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_06.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_06.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_06.setOpaque(true);
        jPanelTablero.add(jLabel60_06);

        jLabel60_07.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_07.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_07.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_07.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_07.setOpaque(true);
        jPanelTablero.add(jLabel60_07);

        jLabel60_08.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_08.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_08.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_08.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_08.setOpaque(true);
        jPanelTablero.add(jLabel60_08);

        jLabel60_09.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_09.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_09.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_09.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_09.setOpaque(true);
        jPanelTablero.add(jLabel60_09);

        jLabel60_10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_10.setOpaque(true);
        jPanelTablero.add(jLabel60_10);

        jLabel60_11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_11.setOpaque(true);
        jPanelTablero.add(jLabel60_11);

        jLabel60_12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_12.setOpaque(true);
        jPanelTablero.add(jLabel60_12);

        jLabel60_13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_13.setOpaque(true);
        jPanelTablero.add(jLabel60_13);

        jLabel60_14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_14.setOpaque(true);
        jPanelTablero.add(jLabel60_14);

        jLabel60_15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_15.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_15.setOpaque(true);
        jPanelTablero.add(jLabel60_15);

        jLabel60_16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_16.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_16.setOpaque(true);
        jPanelTablero.add(jLabel60_16);

        jLabel60_17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_17.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_17.setOpaque(true);
        jPanelTablero.add(jLabel60_17);

        jLabel60_18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_18.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_18.setOpaque(true);
        jPanelTablero.add(jLabel60_18);

        jLabel60_19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_19.setOpaque(true);
        jPanelTablero.add(jLabel60_19);

        jLabel60_20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_20.setOpaque(true);
        jPanelTablero.add(jLabel60_20);

        jLabel60_21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_21.setOpaque(true);
        jPanelTablero.add(jLabel60_21);

        jLabel60_22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_22.setOpaque(true);
        jPanelTablero.add(jLabel60_22);

        jLabel60_23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_23.setOpaque(true);
        jPanelTablero.add(jLabel60_23);

        jLabel60_24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_24.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_24.setOpaque(true);
        jPanelTablero.add(jLabel60_24);

        jLabel60_25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_25.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_25.setOpaque(true);
        jPanelTablero.add(jLabel60_25);

        jLabel60_26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_26.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_26.setOpaque(true);
        jPanelTablero.add(jLabel60_26);

        jLabel60_27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_27.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_27.setOpaque(true);
        jPanelTablero.add(jLabel60_27);

        jLabel60_28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_28.setOpaque(true);
        jPanelTablero.add(jLabel60_28);

        jLabel60_29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_29.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_29.setOpaque(true);
        jPanelTablero.add(jLabel60_29);

        jLabel60_30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_30.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_30.setOpaque(true);
        jPanelTablero.add(jLabel60_30);

        jLabel60_31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_31.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_31.setOpaque(true);
        jPanelTablero.add(jLabel60_31);

        jLabel60_32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_32.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_32.setOpaque(true);
        jPanelTablero.add(jLabel60_32);

        jLabel60_33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_33.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_33.setOpaque(true);
        jPanelTablero.add(jLabel60_33);

        jLabel60_34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_34.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_34.setOpaque(true);
        jPanelTablero.add(jLabel60_34);

        jLabel60_35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_35.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_35.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_35.setOpaque(true);
        jPanelTablero.add(jLabel60_35);

        jLabel60_36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_36.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_36.setOpaque(true);
        jPanelTablero.add(jLabel60_36);

        jLabel60_37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_37.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_37.setOpaque(true);
        jPanelTablero.add(jLabel60_37);

        jLabel60_38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_38.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_38.setOpaque(true);
        jPanelTablero.add(jLabel60_38);

        jLabel60_39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_39.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_39.setOpaque(true);
        jPanelTablero.add(jLabel60_39);

        jLabel60_40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_40.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_40.setOpaque(true);
        jPanelTablero.add(jLabel60_40);

        jLabel60_41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_41.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_41.setOpaque(true);
        jPanelTablero.add(jLabel60_41);

        jLabel60_42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_42.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_42.setOpaque(true);
        jPanelTablero.add(jLabel60_42);

        jLabel60_43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_43.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_43.setOpaque(true);
        jPanelTablero.add(jLabel60_43);

        jLabel60_44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_44.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_44.setOpaque(true);
        jPanelTablero.add(jLabel60_44);

        jLabel60_45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_45.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_45.setOpaque(true);
        jPanelTablero.add(jLabel60_45);

        jLabel60_46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_46.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_46.setOpaque(true);
        jPanelTablero.add(jLabel60_46);

        jLabel60_47.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_47.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_47.setOpaque(true);
        jPanelTablero.add(jLabel60_47);

        jLabel60_48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_48.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_48.setOpaque(true);
        jPanelTablero.add(jLabel60_48);

        jLabel60_49.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_49.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_49.setOpaque(true);
        jPanelTablero.add(jLabel60_49);

        jLabel60_50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_50.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_50.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_50.setOpaque(true);
        jPanelTablero.add(jLabel60_50);

        jLabel60_51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_51.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_51.setOpaque(true);
        jPanelTablero.add(jLabel60_51);

        jLabel60_52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_52.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_52.setOpaque(true);
        jPanelTablero.add(jLabel60_52);

        jLabel60_53.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_53.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_53.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_53.setOpaque(true);
        jPanelTablero.add(jLabel60_53);

        jLabel60_54.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_54.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_54.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_54.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_54.setOpaque(true);
        jPanelTablero.add(jLabel60_54);

        jLabel60_55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_55.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_55.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_55.setOpaque(true);
        jPanelTablero.add(jLabel60_55);

        jLabel60_56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_56.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_56.setOpaque(true);
        jPanelTablero.add(jLabel60_56);

        jLabel60_57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_57.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_57.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_57.setOpaque(true);
        jPanelTablero.add(jLabel60_57);

        jLabel60_58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_58.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_58.setOpaque(true);
        jPanelTablero.add(jLabel60_58);

        jLabel60_59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel60_59.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel60_59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60_59.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel60_59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60_59.setOpaque(true);
        jPanelTablero.add(jLabel60_59);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("1");
        jToggleButton1.setToolTipText("");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("3");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("4");
        jToggleButton4.setToolTipText("");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setText("6");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setText("7");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setText("8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setText("9");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setText("10");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setText("11");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setText("12");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButtonBorrar);
        jToggleButtonBorrar.setText("borrar");
        jToggleButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBorrarActionPerformed(evt);
            }
        });

        jButton1.setText("Resolver Celda");

        jButton2.setText("Solución");

        jButton3.setText("Comprobar");

        jButtonGenera.setText("Generar Tablero");
        jButtonGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneraActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("pruebas");

        javax.swing.GroupLayout jBasePanelLayout = new javax.swing.GroupLayout(jBasePanel);
        jBasePanel.setLayout(jBasePanelLayout);
        jBasePanelLayout.setHorizontalGroup(
            jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBasePanelLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jBasePanelLayout.createSequentialGroup()
                        .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButtonBorrar)
                            .addComponent(jButtonGenera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jBasePanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jBasePanelLayout.createSequentialGroup()
                                .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jBasePanelLayout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jBasePanelLayout.createSequentialGroup()
                                        .addComponent(jToggleButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jToggleButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton8)))
                                .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jBasePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jToggleButton12))
                                    .addGroup(jBasePanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)))))
                .addGap(138, 138, 138))
        );
        jBasePanelLayout.setVerticalGroup(
            jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBasePanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGenera, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jBasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        HourMazeMenu.setText("Hour Maze");

        NuevoTableroMenu.setText("Nuevo Tablero");

        Item24.setText("24 Celdas (4x6)");
        Item24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item24ActionPerformed(evt);
            }
        });
        NuevoTableroMenu.add(Item24);

        Item36.setText("36 Celdas (4x9)");
        Item36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item36ActionPerformed(evt);
            }
        });
        NuevoTableroMenu.add(Item36);

        Item48.setText("48 Celdas (6x8)");
        Item48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item48ActionPerformed(evt);
            }
        });
        NuevoTableroMenu.add(Item48);

        Item60.setText("60 Celdas (6x10)");
        Item60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item60ActionPerformed(evt);
            }
        });
        NuevoTableroMenu.add(Item60);

        HourMazeMenu.add(NuevoTableroMenu);

        InfoMenu.setText("Acerca de");
        HourMazeMenu.add(InfoMenu);

        jMenuBar1.add(HourMazeMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jBasePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jBasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item36ActionPerformed
        tam = 36;
        limpiaTableroGUI();
        prepararTableroGUI(tam);
    }//GEN-LAST:event_Item36ActionPerformed

    private void Item24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item24ActionPerformed
        tam = 24;
        limpiaTableroGUI();
        prepararTableroGUI(tam);
    }//GEN-LAST:event_Item24ActionPerformed

    private void Item48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item48ActionPerformed
        tam = 48;
        limpiaTableroGUI();
        prepararTableroGUI(tam);
    }//GEN-LAST:event_Item48ActionPerformed

    private void Item60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item60ActionPerformed
        tam = 60;
        limpiaTableroGUI();
        prepararTableroGUI(tam);
    }//GEN-LAST:event_Item60ActionPerformed

    private void jButtonGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeneraActionPerformed
        limpiaTableroGUI();
        generaTablero();
        imprimeTableroGUI(tableroInicial);
    }//GEN-LAST:event_jButtonGeneraActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        valorPulsado = "1";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        valorPulsado = "2";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        valorPulsado = "3";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        valorPulsado = "4";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        valorPulsado = "5";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        valorPulsado = "6";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        valorPulsado = "7";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        valorPulsado = "8";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        valorPulsado = "9";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        valorPulsado = "10";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        valorPulsado = "11";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        valorPulsado = "12";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBorrarActionPerformed
        valorPulsado = "borrar";
        jLabel1.setText("se ha pulsado: " + valorPulsado);
    }//GEN-LAST:event_jToggleButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HourMaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HourMaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HourMaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HourMaze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HourMaze().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu HourMazeMenu;
    private javax.swing.JMenuItem InfoMenu;
    private javax.swing.JMenuItem Item24;
    private javax.swing.JMenuItem Item36;
    private javax.swing.JMenuItem Item48;
    private javax.swing.JMenuItem Item60;
    private javax.swing.JMenu NuevoTableroMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jBasePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonGenera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24_00;
    private javax.swing.JLabel jLabel24_01;
    private javax.swing.JLabel jLabel24_02;
    private javax.swing.JLabel jLabel24_03;
    private javax.swing.JLabel jLabel24_04;
    private javax.swing.JLabel jLabel24_05;
    private javax.swing.JLabel jLabel24_10;
    private javax.swing.JLabel jLabel24_11;
    private javax.swing.JLabel jLabel24_12;
    private javax.swing.JLabel jLabel24_13;
    private javax.swing.JLabel jLabel24_14;
    private javax.swing.JLabel jLabel24_15;
    private javax.swing.JLabel jLabel24_20;
    private javax.swing.JLabel jLabel24_21;
    private javax.swing.JLabel jLabel24_22;
    private javax.swing.JLabel jLabel24_23;
    private javax.swing.JLabel jLabel24_24;
    private javax.swing.JLabel jLabel24_25;
    private javax.swing.JLabel jLabel24_30;
    private javax.swing.JLabel jLabel24_31;
    private javax.swing.JLabel jLabel24_32;
    private javax.swing.JLabel jLabel24_33;
    private javax.swing.JLabel jLabel24_34;
    private javax.swing.JLabel jLabel24_35;
    private javax.swing.JLabel jLabel60_00;
    private javax.swing.JLabel jLabel60_01;
    private javax.swing.JLabel jLabel60_02;
    private javax.swing.JLabel jLabel60_03;
    private javax.swing.JLabel jLabel60_04;
    private javax.swing.JLabel jLabel60_05;
    private javax.swing.JLabel jLabel60_06;
    private javax.swing.JLabel jLabel60_07;
    private javax.swing.JLabel jLabel60_08;
    private javax.swing.JLabel jLabel60_09;
    private javax.swing.JLabel jLabel60_10;
    private javax.swing.JLabel jLabel60_11;
    private javax.swing.JLabel jLabel60_12;
    private javax.swing.JLabel jLabel60_13;
    private javax.swing.JLabel jLabel60_14;
    private javax.swing.JLabel jLabel60_15;
    private javax.swing.JLabel jLabel60_16;
    private javax.swing.JLabel jLabel60_17;
    private javax.swing.JLabel jLabel60_18;
    private javax.swing.JLabel jLabel60_19;
    private javax.swing.JLabel jLabel60_20;
    private javax.swing.JLabel jLabel60_21;
    private javax.swing.JLabel jLabel60_22;
    private javax.swing.JLabel jLabel60_23;
    private javax.swing.JLabel jLabel60_24;
    private javax.swing.JLabel jLabel60_25;
    private javax.swing.JLabel jLabel60_26;
    private javax.swing.JLabel jLabel60_27;
    private javax.swing.JLabel jLabel60_28;
    private javax.swing.JLabel jLabel60_29;
    private javax.swing.JLabel jLabel60_30;
    private javax.swing.JLabel jLabel60_31;
    private javax.swing.JLabel jLabel60_32;
    private javax.swing.JLabel jLabel60_33;
    private javax.swing.JLabel jLabel60_34;
    private javax.swing.JLabel jLabel60_35;
    private javax.swing.JLabel jLabel60_36;
    private javax.swing.JLabel jLabel60_37;
    private javax.swing.JLabel jLabel60_38;
    private javax.swing.JLabel jLabel60_39;
    private javax.swing.JLabel jLabel60_40;
    private javax.swing.JLabel jLabel60_41;
    private javax.swing.JLabel jLabel60_42;
    private javax.swing.JLabel jLabel60_43;
    private javax.swing.JLabel jLabel60_44;
    private javax.swing.JLabel jLabel60_45;
    private javax.swing.JLabel jLabel60_46;
    private javax.swing.JLabel jLabel60_47;
    private javax.swing.JLabel jLabel60_48;
    private javax.swing.JLabel jLabel60_49;
    private javax.swing.JLabel jLabel60_50;
    private javax.swing.JLabel jLabel60_51;
    private javax.swing.JLabel jLabel60_52;
    private javax.swing.JLabel jLabel60_53;
    private javax.swing.JLabel jLabel60_54;
    private javax.swing.JLabel jLabel60_55;
    private javax.swing.JLabel jLabel60_56;
    private javax.swing.JLabel jLabel60_57;
    private javax.swing.JLabel jLabel60_58;
    private javax.swing.JLabel jLabel60_59;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanelTablero;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JToggleButton jToggleButtonBorrar;
    // End of variables declaration//GEN-END:variables

    //------------ Variables adicionales -------------/
    private Tablero tableroSolucion, tableroInicial;
    private JLabel[][] tableroGUI;
    private int tam;
    private String valorPulsado;
    
    
    
    //------------- Métodos Adicionales --------------------/   
    
    private void prepararTableroGUI(int tam) {   
        switch (tam){
            case 24:
                for(int i=0;i<6;i++){
                    for(int j=0;j<10;j++){
                        if(i>=4 || j>=6){
                            tableroGUI[i][j].setVisible(false);
                        }
                        else{
                            tableroGUI[i][j].setVisible(true);
                        }
                    }
                }
                break;
            case 36:
                for(int i=0;i<6;i++){
                    for(int j=0;j<10;j++){
                        if(i>=4 || j>=9){
                            tableroGUI[i][j].setVisible(false);
                        }
                        else{
                            tableroGUI[i][j].setVisible(true);
                        }
                    }
                }
                break;
            case 48:
                for(int i=0;i<6;i++){
                    for(int j=0;j<10;j++){
                        if(i>=6 || j>=8){
                            tableroGUI[i][j].setVisible(false);
                        }
                        else{
                            tableroGUI[i][j].setVisible(true);
                        }
                    }
                }
                break;
            case 60: 
                for(int i=0;i<6;i++){
                    for(int j=0;j<10;j++){
                        tableroGUI[i][j].setVisible(true);
                    }
                }
                break;     
        }
    }

    private void inicializaGUI() {
        tableroGUI = new JLabel[6][10];
        tableroGUI[0][0] = jLabel60_00;
        tableroGUI[0][1] = jLabel60_01;
        tableroGUI[0][2] = jLabel60_02;
        tableroGUI[0][3] = jLabel60_03;
        tableroGUI[0][4] = jLabel60_04;
        tableroGUI[0][5] = jLabel60_05;
        tableroGUI[0][6] = jLabel60_06;
        tableroGUI[0][7] = jLabel60_07;
        tableroGUI[0][8] = jLabel60_08;
        tableroGUI[0][9] = jLabel60_09;
        tableroGUI[1][0] = jLabel60_10;
        tableroGUI[1][1] = jLabel60_11;
        tableroGUI[1][2] = jLabel60_12;
        tableroGUI[1][3] = jLabel60_13;
        tableroGUI[1][4] = jLabel60_14;
        tableroGUI[1][5] = jLabel60_15;
        tableroGUI[1][6] = jLabel60_16;
        tableroGUI[1][7] = jLabel60_17;
        tableroGUI[1][8] = jLabel60_18;
        tableroGUI[1][9] = jLabel60_19;
        tableroGUI[2][0] = jLabel60_20;
        tableroGUI[2][1] = jLabel60_21;
        tableroGUI[2][2] = jLabel60_22;
        tableroGUI[2][3] = jLabel60_23;
        tableroGUI[2][4] = jLabel60_24;
        tableroGUI[2][5] = jLabel60_25;
        tableroGUI[2][6] = jLabel60_26;
        tableroGUI[2][7] = jLabel60_27;
        tableroGUI[2][8] = jLabel60_28;
        tableroGUI[2][9] = jLabel60_29;
        tableroGUI[3][0] = jLabel60_30;
        tableroGUI[3][1] = jLabel60_31;
        tableroGUI[3][2] = jLabel60_32;
        tableroGUI[3][3] = jLabel60_33;
        tableroGUI[3][4] = jLabel60_34;
        tableroGUI[3][5] = jLabel60_35;
        tableroGUI[3][6] = jLabel60_36;
        tableroGUI[3][7] = jLabel60_37;
        tableroGUI[3][8] = jLabel60_38;
        tableroGUI[3][9] = jLabel60_39;
        tableroGUI[4][0] = jLabel60_40;
        tableroGUI[4][1] = jLabel60_41;
        tableroGUI[4][2] = jLabel60_42;
        tableroGUI[4][3] = jLabel60_43;
        tableroGUI[4][4] = jLabel60_44;
        tableroGUI[4][5] = jLabel60_45;
        tableroGUI[4][6] = jLabel60_46;
        tableroGUI[4][7] = jLabel60_47;
        tableroGUI[4][8] = jLabel60_48;
        tableroGUI[4][9] = jLabel60_49;
        tableroGUI[5][0] = jLabel60_50;
        tableroGUI[5][1] = jLabel60_51;
        tableroGUI[5][2] = jLabel60_52;
        tableroGUI[5][3] = jLabel60_53;
        tableroGUI[5][4] = jLabel60_54;
        tableroGUI[5][5] = jLabel60_55;
        tableroGUI[5][6] = jLabel60_56;
        tableroGUI[5][7] = jLabel60_57;
        tableroGUI[5][8] = jLabel60_58;
        tableroGUI[5][9] = jLabel60_59;
        tam = 60;
        prepararTableroGUI(60);
    }

    private void generaTablero() {
        tableroSolucion = new Tablero(tam); 
        Solucion.creaSolucion(tableroSolucion);
        tableroInicial = Solucion.creaTableroInicial(tableroSolucion);
    }
    
    private void imprimeTableroGUI(Tablero t){
        Celda[][] tab = t.getTablero();
        Celda celda;
        int muroAbajo, muroArriba, muroIzquierda, muroDerecha;
        
        for(int i=0;i<t.getFilas();i++){
            for(int j=0;j<t.getCol();j++){
                celda = tab[i][j];
                muroAbajo = 1;
                muroArriba = 1;
                muroIzquierda = 1;
                muroDerecha = 1;
                if(celda.getValor() != 0){
                    tableroGUI[i][j].setText(Integer.toString(celda.getValor()));
                    tableroGUI[i][j].setBackground(new java.awt.Color(200, 200, 200));
                }
                if(celda.isMuroAbajo()){
                    muroAbajo = 4;
                }
                if(celda.isMuroArriba()){
                    muroArriba = 4;
                }
                if(celda.isMuroDerecha()){
                    muroDerecha = 4;
                }
                if(celda.isMuroIzquierda()){
                    muroIzquierda = 4;
                }
                tableroGUI[i][j].setBorder(javax.swing.BorderFactory.createMatteBorder(muroArriba, muroIzquierda, muroAbajo, muroDerecha, Color.DARK_GRAY));
            }
        }
    }

    private void limpiaTableroGUI() {
        for(int i=0;i<6;i++){
            for(int j=0;j<10;j++){
                tableroGUI[i][j].setText("");
                tableroGUI[i][j].setBackground(Color.WHITE);
                tableroGUI[i][j].setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.DARK_GRAY));
            }
        }
    }
    
    
}
